import { env, type Env } from "./env.js";

export const appEnv: Pick<
  Env,
  | "APP_ENV"
  | "APP_NAME"
  | "LOG_PRETTY"
  | "WORKER_ALLOWED_ORIGINS"
  | "WORKER_BODY_LIMIT_BYTES"
  | "WORKER_HOST"
  | "WORKER_PORT"
  | "WORKER_REQUEST_TIMEOUT_MS"
  | "WORKER_SERVICE_TOKEN"
> = env;

export const databaseEnv: Pick<
  Env,
  | "DATABASE_POOL_MAX"
  | "DATABASE_POOL_MIN"
  | "DATABASE_STATEMENT_TIMEOUT_MS"
  | "DATABASE_URL"
> = env;

export const offerEnv: Pick<
  Env,
  | "DEFAULT_CURRENCY"
  | "MAX_AUTOMATIC_DISCOUNT_PERCENT"
  | "MAX_PRICE_CENTS"
  | "MIN_DISCOUNT_PERCENT"
  | "MIN_PRICE_CENTS"
> = env;

export const publicationEnv: Pick<
  Env,
  | "MAX_PUBLICATIONS_PER_DAY"
  | "MAX_PUBLICATIONS_PER_HOUR"
  | "PUBLICATION_MIN_INTERVAL_SECONDS"
  | "TELEGRAM_MAX_CAPTION_LENGTH"
  | "TELEGRAM_RICH_TEXT_ENABLED"
> = env;

export const telegramEnv: Pick<
  Env,
  | "TELEGRAM_ADMIN_USER_IDS"
  | "TELEGRAM_APPROVAL_CHAT_ID"
  | "TELEGRAM_BOT_API_BASE"
  | "TELEGRAM_BOT_TOKEN"
  | "TELEGRAM_CHANNEL_APPLIANCES_ID"
  | "TELEGRAM_CHANNEL_BEAUTY_ID"
  | "TELEGRAM_CHANNEL_ELECTRONICS_ID"
  | "TELEGRAM_CHANNEL_HARDWARE_ID"
  | "TELEGRAM_CHANNEL_HOME_KITCHEN_ID"
  | "TELEGRAM_DISABLE_NOTIFICATION"
  | "TELEGRAM_PARSE_MODE"
  | "TELEGRAM_POLLING_ENABLED"
  | "TELEGRAM_PROTECT_CONTENT"
  | "TELEGRAM_PUBLIC_CHANNEL_ID"
  | "TELEGRAM_RICH_TEXT_ENABLED"
  | "TELEGRAM_WEBHOOK_SECRET"
> = env;

export const mercadoLivreEnv: Pick<
  Env,
  | "AFFILIATE_ALLOWED_DOMAINS"
  | "AFFILIATE_REQUIRE_HTTPS"
  | "MERCADOLIVRE_AFFILIATE_AUTOMATION_ENABLED"
  | "MERCADOLIVRE_AFFILIATE_PORTAL_URL"
  | "MERCADOLIVRE_AFFILIATE_SESSION_NAME"
  | "MERCADOLIVRE_API_BASE_URL"
  | "MERCADOLIVRE_AUTH_BASE_URL"
  | "MERCADOLIVRE_CLIENT_ID"
  | "MERCADOLIVRE_CLIENT_SECRET"
  | "MERCADOLIVRE_REDIRECT_URI"
  | "SOURCE_MERCADOLIVRE_ENABLED"
  | "SOURCE_MERCADOLIVRE_MAX_PAGES_PER_RUN"
> = env;

export const marketplaceEnv: Pick<
  Env,
  | "ALIEXPRESS_AFFILIATE_API_URL"
  | "ALIEXPRESS_APP_KEY"
  | "ALIEXPRESS_APP_SECRET"
  | "ALIEXPRESS_TRACKING_ID"
  | "SHOPEE_AFFILIATE_API_URL"
  | "SHOPEE_APP_ID"
  | "SHOPEE_SECRET"
  | "SOURCE_ALIEXPRESS_ENABLED"
  | "SOURCE_SHOPEE_ENABLED"
> = env;

export const discoveryEnv: Pick<Env, "TZ"> = env;
